export default function Head() {
  return (
    <>
      <title>Faturar</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logo.png" />

      <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet' precedence="default" />
    </>
  )
}
